language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.7.8"
  - DJANGO="Django==1.8.1"
 
install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install pytz
  - pip install coveralls
  - python setup.py develop

script:
  - cd example_project; coverage run manage.py test photologue

after_success:
  - coveralls

